SELECT DISTINCT(H.CAR_ID), C.CAR_TYPE, CEILING(C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C
ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV') AND
    500000 <= C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30 AND
    C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30 < 2000000 AND
    H.CAR_ID NOT IN
        (SELECT CAR_ID
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
         WHERE '2022-11-30' >= START_DATE AND '2022-11-01' <= END_DATE)
ORDER BY FEE DESC, C.CAR_TYPE, H.CAR_ID DESC;
