SELECT P.ITEM_ID, P.ITEM_NAME, P.RARITY
FROM ITEM_INFO AS I JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.PARENT_ITEM_ID
LEFT JOIN ITEM_INFO AS P
ON T.ITEM_ID = P.ITEM_ID
WHERE I.RARITY = 'RARE'
ORDER BY P.ITEM_ID DESC;
