SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, LEFT(R.CREATED_DATE,10) AS CREATED_DATE
FROM USED_GOODS_BOARD AS B RIGHT JOIN USED_GOODS_REPLY AS R
ON B.BOARD_ID = R.BOARD_ID
WHERE LEFT(B.CREATED_DATE,7)='2022-10'
ORDER BY R.CREATED_DATE, B.TITLE;
